// AUTO-GENERATED by scripts/build-assets.mjs — do not edit manually

const PROD_BASE = "https://cdn.carleton.ca/rds/assets";
const DEV_BASE = "/_assets";

const viteDev =
  typeof import.meta !== 'undefined' &&
  (import.meta as ImportMeta & { env?: { DEV?: boolean } }).env?.DEV === true;

const nodeDev =
  (globalThis as { process?: { env?: { NODE_ENV?: string } } }).process?.env?.NODE_ENV ===
  'development';

const isDev = viteDev || nodeDev;

export const ASSET_BASE = isDev ? DEV_BASE : PROD_BASE;

export const assets = {
  bgArise1: `${ASSET_BASE}/bg-images/arise-1.jpg`,
  bgArise2: `${ASSET_BASE}/bg-images/arise-2.jpg`,
  bgLeeds: `${ASSET_BASE}/bg-images/leeds.jpg`,
  bgLibrary: `${ASSET_BASE}/bg-images/library.jpg`,
  bgNicol: `${ASSET_BASE}/bg-images/nicol.jpg`,
  bgSoutham: `${ASSET_BASE}/bg-images/southam.jpg`,
  bgSplashAthletics: `${ASSET_BASE}/bg-images/splash-athletics.png`,
  bgTory: `${ASSET_BASE}/bg-images/tory.jpg`,
  campusAerial01: `${ASSET_BASE}/banners/campus-aerial-01.jpg`,
  campusRiver01: `${ASSET_BASE}/banners/campus-river-01.jpg`,
  cuLogoBlackLeftHorizontal: `${ASSET_BASE}/cu-logos/cu-logo-black-left-horizontal.svg`,
  cuLogoBlackLeftHorizontalOutlined: `${ASSET_BASE}/cu-logos/cu-logo-black-left-horizontal-outlined.svg`,
  cuLogoBlackRightHorizontal: `${ASSET_BASE}/cu-logos/cu-logo-black-right-horizontal.svg`,
  cuLogoBlackRightHorizontalOutlined: `${ASSET_BASE}/cu-logos/cu-logo-black-right-horizontal-outlined.svg`,
  cuLogoBlackVertical: `${ASSET_BASE}/cu-logos/cu-logo-black-vertical.svg`,
  cuLogoBlackVerticalOutlined: `${ASSET_BASE}/cu-logos/cu-logo-black-vertical-outlined.svg`,
  cuLogoCarleton360: `${ASSET_BASE}/cu-logos/cu-logo-carleton360.svg`,
  cuLogoColorLeftHorizontal: `${ASSET_BASE}/cu-logos/cu-logo-color-left-horiztonal.svg`,
  cuLogoColorLeftHorizontalOutlined: `${ASSET_BASE}/cu-logos/cu-logo-color-left-horizontal-outlined.svg`,
  cuLogoColorRightHorizontal: `${ASSET_BASE}/cu-logos/cu-logo-color-right-horiztonal.svg`,
  cuLogoColorRightHorizontalOutlined: `${ASSET_BASE}/cu-logos/cu-logo-color-right-horizontal-outlined.svg`,
  cuLogoColorVertical: `${ASSET_BASE}/cu-logos/cu-logo-color-vertical.svg`,
  cuLogoColorVerticalOutlined: `${ASSET_BASE}/cu-logos/cu-logo-color-vertical-outlined.svg`,
  cuRavensLogoWhite: `${ASSET_BASE}/graphics/cu-ravens-logo-white.svg`,
  cuShieldBlack: `${ASSET_BASE}/cu-logos/cu-shield-black.svg`,
  cuShieldBlackOutlined: `${ASSET_BASE}/cu-logos/cu-shield-black-outlined.svg`,
  cuShieldColor: `${ASSET_BASE}/cu-logos/cu-shield-color.svg`,
  cuShieldColorOutlined: `${ASSET_BASE}/cu-logos/cu-shield-color-outlined.svg`,
  cuWavesFooterRed: `${ASSET_BASE}/graphics/cu-waves-footer-red.svg`,
  cuWavesHardEdgeBlack: `${ASSET_BASE}/graphics/cu-waves-hard-edge-black.svg`,
  cuWavesHardEdgeRed: `${ASSET_BASE}/graphics/cu-waves-hard-edge-red.svg`,
  cuWavesRepeatingBottomRed: `${ASSET_BASE}/graphics/cu-waves-repeating-bottom-red.svg`,
  favicon16: `${ASSET_BASE}/favicons/favicon-16x16.png`,
  favicon32: `${ASSET_BASE}/favicons/favicon-32x32.png`,
  favicon48: `${ASSET_BASE}/favicons/favicon-48x48.png`,
  faviconAndroidChrome192: `${ASSET_BASE}/favicons/android-chrome-192x192.png`,
  faviconAndroidChrome512: `${ASSET_BASE}/favicons/android-chrome-512x512.png`,
  faviconAppleTouch: `${ASSET_BASE}/favicons/apple-touch-icon.png`,
  faviconIco: `${ASSET_BASE}/favicons/favicon.ico`,
  faviconMstile150: `${ASSET_BASE}/favicons/mstile-150x150.png`,
  faviconSafariPinnedTab: `${ASSET_BASE}/favicons/safari-pinned-tab.svg`,
  fontawesomeLight: `${ASSET_BASE}/graphics/fontawesome-light.svg`,
  greyBg: `${ASSET_BASE}/graphics/grey-bg.jpg`,
  iconXSolid: `${ASSET_BASE}/icons/x-solid.svg`,
  lexicalAlignCenter: `${ASSET_BASE}/lexical-icons/align-center-light.svg`,
  lexicalAlignJustify: `${ASSET_BASE}/lexical-icons/align-justify-light.svg`,
  lexicalAlignLeft: `${ASSET_BASE}/lexical-icons/align-left-light.svg`,
  lexicalAlignRight: `${ASSET_BASE}/lexical-icons/align-right-light.svg`,
  lexicalBold: `${ASSET_BASE}/lexical-icons/bold-light.svg`,
  lexicalChevronDown: `${ASSET_BASE}/lexical-icons/chevron-down-light.svg`,
  lexicalH2: `${ASSET_BASE}/lexical-icons/h2-light.svg`,
  lexicalH3: `${ASSET_BASE}/lexical-icons/h3-light.svg`,
  lexicalH4: `${ASSET_BASE}/lexical-icons/h4-light.svg`,
  lexicalImage: `${ASSET_BASE}/lexical-icons/image-regular.svg`,
  lexicalItalic: `${ASSET_BASE}/lexical-icons/italic-light.svg`,
  lexicalLink: `${ASSET_BASE}/lexical-icons/link-light.svg`,
  lexicalListOl: `${ASSET_BASE}/lexical-icons/list-ol-light.svg`,
  lexicalListUl: `${ASSET_BASE}/lexical-icons/list-ul-light.svg`,
  lexicalMessageQuote: `${ASSET_BASE}/lexical-icons/message-quote-light.svg`,
  lexicalParagraph: `${ASSET_BASE}/lexical-icons/paragraph-light.svg`,
  lexicalPencil: `${ASSET_BASE}/lexical-icons/pencil-light.svg`,
  lexicalRotateLeft: `${ASSET_BASE}/lexical-icons/rotate-left-light.svg`,
  lexicalRotateRight: `${ASSET_BASE}/lexical-icons/rotate-right-light.svg`,
  lexicalUnderline: `${ASSET_BASE}/lexical-icons/underline-light.svg`,
  quoteRed10: `${ASSET_BASE}/graphics/quote-red-10.svg`,
  quoteWhite: `${ASSET_BASE}/graphics/quote-white.svg`,
  ravensLogo: `${ASSET_BASE}/ravens-logos/ravens-logo.svg`,
  ravensLogoWordmark: `${ASSET_BASE}/ravens-logos/ravens-logo-wordmark.svg`,
} as const;

export type AssetKey = keyof typeof assets;
