import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const configPath = resolve(root, 'src/config/assets.json');
const tsOutPath = resolve(root, 'src/config/assets.ts');
const scssOutPath = resolve(root, 'src/styles/auto/_assets.scss');
const scssDevOutPath = resolve(root, 'src/styles/auto/_assets-dev.scss');

const kebabToCamel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

const { baseUrl, devBaseUrl, paths } = JSON.parse(await readFile(configPath, 'utf8'));

const entries = Object.entries(paths).sort(([a], [b]) => a.localeCompare(b));

const tsLines = [
  '// AUTO-GENERATED by scripts/build-assets.mjs — do not edit manually',
  '',
  `const PROD_BASE = ${JSON.stringify(baseUrl)};`,
  `const DEV_BASE = ${JSON.stringify(devBaseUrl)};`,
  '',
  'const viteDev =',
  "  typeof import.meta !== 'undefined' &&",
  '  (import.meta as ImportMeta & { env?: { DEV?: boolean } }).env?.DEV === true;',
  '',
  'const nodeDev =',
  "  (globalThis as { process?: { env?: { NODE_ENV?: string } } }).process?.env?.NODE_ENV ===",
  "  'development';",
  '',
  'const isDev = viteDev || nodeDev;',
  '',
  'export const ASSET_BASE = isDev ? DEV_BASE : PROD_BASE;',
  '',
  'export const assets = {',
];
for (const [key, path] of entries) {
  tsLines.push(`  ${kebabToCamel(key)}: \`\${ASSET_BASE}/${path}\`,`);
}
tsLines.push('} as const;', '', 'export type AssetKey = keyof typeof assets;', '');

await writeFile(tsOutPath, tsLines.join('\n'));

const scssProdLines = [
  '// AUTO-GENERATED by scripts/build-assets.mjs — do not edit manually',
  '',
  ':root {',
];
for (const [key, path] of entries) {
  scssProdLines.push(`  --rds--asset-${key}: url('${baseUrl}/${path}');`);
}
scssProdLines.push('}', '');
await writeFile(scssOutPath, scssProdLines.join('\n'));

const scssDevLines = [
  '// AUTO-GENERATED by scripts/build-assets.mjs — do not edit manually',
  '// Imported by Storybook preview to point --rds--asset-* at locally-served files',
  '',
  ':root {',
];
for (const [key, path] of entries) {
  scssDevLines.push(`  --rds--asset-${key}: url('${devBaseUrl}/${path}');`);
}
scssDevLines.push('}', '');
await mkdir(dirname(scssDevOutPath), { recursive: true });
await writeFile(scssDevOutPath, scssDevLines.join('\n'));

console.log(`  ✓ src/config/assets.ts (${entries.length} keys)`);
console.log(`  ✓ src/styles/auto/_assets.scss`);
console.log(`  ✓ src/styles/auto/_assets-dev.scss`);
