import { readdir, readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { join, resolve, dirname, parse } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const svgDir = join(root, 'src/icons/svg');
const outDir = join(root, 'src/icons/generated');
const listPath = join(root, 'src/icons/iconList.ts');

const kebabToPascal = (name) =>
  name
    .split('-')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');

const formatLabel = (name) =>
  name.replace(/-/g, ' ').replace(/^\w/, (c) => c.toUpperCase());

const svgAttrsToJsx = (inner) =>
  inner
    .replace(/\s+fill="[^"]*"/g, '')
    .replace(/([a-z]+)-([a-z])/g, (_, a, b) => a + b.toUpperCase());

const parseSvg = (source, name) => {
  const noComments = source.replace(/<!--[\s\S]*?-->/g, '');
  const svgMatch = noComments.match(/<svg([^>]*)>([\s\S]*)<\/svg>/);
  if (!svgMatch) throw new Error(`Could not parse ${name}.svg`);
  const attrs = svgMatch[1];
  const inner = svgMatch[2].trim();
  const viewBox = attrs.match(/viewBox="([^"]+)"/)?.[1] ?? '0 0 512 512';
  const innerJsx = svgAttrsToJsx(inner);
  return { viewBox, innerJsx };
};

const componentTemplate = (pascalName, viewBox, innerJsx) => `import type { SVGProps } from 'react';

export const ${pascalName}Icon = (props: SVGProps<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}" fill="currentColor" {...props}>
    ${innerJsx}
  </svg>
);
`;

async function main() {
  const files = await readdir(svgDir);
  const svgFiles = files.filter((f) => f.endsWith('.svg')).sort();

  if (svgFiles.length === 0) {
    console.warn('No SVG files found in', svgDir);
    return;
  }

  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const icons = [];
  for (const file of svgFiles) {
    const name = parse(file).name;
    const pascal = kebabToPascal(name);
    const source = await readFile(join(svgDir, file), 'utf8');
    const { viewBox, innerJsx } = parseSvg(source, name);
    await writeFile(join(outDir, `${name}.tsx`), componentTemplate(pascal, viewBox, innerJsx));
    icons.push({ name, pascal, label: formatLabel(name) });
  }

  const registryImports = icons
    .map((i) => `import { ${i.pascal}Icon } from './${i.name}';`)
    .join('\n');
  const registryEntries = icons.map((i) => `  '${i.name}': ${i.pascal}Icon,`).join('\n');
  const namedReexports = icons
    .map((i) => `export { ${i.pascal}Icon } from './${i.name}';`)
    .join('\n');

  const registryFile = `${registryImports}

export const iconMap = {
${registryEntries}
} as const;

export type IconName = keyof typeof iconMap;

${namedReexports}
`;
  await writeFile(join(outDir, 'registry.ts'), registryFile);

  const listEntries = icons
    .map((i) => `  { value: '${i.name}', label: '${i.label}' },`)
    .join('\n');
  const listFile = `// Auto-generated by scripts/generate-icons.mjs — do not edit manually

export interface IconListEntry {
  value: string;
  label: string;
}

export const iconList: readonly IconListEntry[] = [
${listEntries}
] as const;
`;
  await writeFile(listPath, listFile);

  console.log(`  ✓ Generated ${icons.length} icon components in ${outDir}`);
  console.log(`  ✓ Generated iconList at ${listPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
